尝试确定格式
naichabaobao/jass pull request #29
Opened 2023-07-14 03:23 UTC by jzy-chitong56

因为你没有发版，本地测试不到效果
只能先补充一点，看看这样写是不是正确的  
有问题请改一条正确的作为参照
我确实不知道中括号里面要不要引号

2023-07-16 01:45 UTC, naichabaobao requested changes
你不会用json吗？CHANGELOG.md这文件更新时不是说明了吗。

2023-07-16 01:48 UTC, naichabaobao commented
不要提供这种字符串，最好就提供代码用得着的，譬如，"chest"，"BACKDROP"这种。

2023-07-20 10:07 UTC, jzy-chitong56 commented
不会代码

2023-07-21 02:22 UTC, naichabaobao commented
你只要安装node跟typescript就行了，然后直接在vscode测试，未完成预期发行有点奇怪。

2023-07-21 02:26 UTC, merged

2023-07-21 02:28 UTC, naichabaobao commented
你新建一个文件吧，一行行写上，譬如 "chest" "胸部点"

2023-07-21 02:28 UTC, naichabaobao commented
我自己整理合并，你提供中文就行